global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # IPv6 Toolkit metrics
  - job_name: 'ipv6kit'
    static_configs:
      - targets: ['localhost:9091']  # Your IPv6 toolkit metrics port
    scrape_interval: 5s  # Scrape more frequently for real-time monitoring
    metrics_path: '/metrics'
    
    # Optional: Add labels to identify this service
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'ipv6kit' 