[package]
name = "probe"
version = "0.1.0"
edition = "2024"

[dependencies]
# polars = { workspace = true }
# serde = { workspace = true }
# serde_json = { workspace = true }
anyhow = { workspace = true }
pnet = "0.35.0" 