[package]
name = "view"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { workspace = true, features = ["lazy", "csv"] }
ratatui = { version = "0.26.1", features = ["all-widgets"] }
crossterm = "0.27.0"
anyhow.workspace = true
